version: "3.9"


services:
    backend:
      build: 
        context: .
      container_name: django
      command: python manage.py runserver 0.0.0.0:8000
      ports:
        - "8000:8000"
      volumes:
        - ./app/:/backend/app/
        - node:/backend/node_modules/
      depends_on:
        - pgdb

    node_modules:
      build:
        context: ./npm.conf
      container_name: npm
      volumes: 
        - node:/modules/

    pgdb:
      image: postgres:13
      restart: always
      container_name: pgdb
      hostname: pgdb
      expose:
        - 5432
      ports:
        - "5432:5432"
      environment:
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_USER=postgres
        - POSTGRES_DB=postgres
      volumes:
        - pgdb_directory:/var/lib/postgresql/data9

volumes:
  pgdb_directory: 
  node:  