name: Test and lint 
on: 
  push:
    branches:
      - main 
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: run docker
        run: docker-compose build
      - name: Test Lint
        run: docker-compose run --rm backend flake8 --config config.cfg
